# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import matricula_pb2 as matricula__pb2


class MatriculaServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.cadastraNota = channel.unary_unary(
        '/matricula.MatriculaService/cadastraNota',
        request_serializer=matricula__pb2.Matricula.SerializeToString,
        response_deserializer=matricula__pb2.Mess.FromString,
        )
    self.atualizaNota = channel.unary_unary(
        '/matricula.MatriculaService/atualizaNota',
        request_serializer=matricula__pb2.Matricula.SerializeToString,
        response_deserializer=matricula__pb2.Mess.FromString,
        )
    self.removeNota = channel.unary_unary(
        '/matricula.MatriculaService/removeNota',
        request_serializer=matricula__pb2.Matricula.SerializeToString,
        response_deserializer=matricula__pb2.Mess.FromString,
        )
    self.consultaNota = channel.unary_unary(
        '/matricula.MatriculaService/consultaNota',
        request_serializer=matricula__pb2.Matricula.SerializeToString,
        response_deserializer=matricula__pb2.Mess.FromString,
        )
    self.consultaFalta = channel.unary_unary(
        '/matricula.MatriculaService/consultaFalta',
        request_serializer=matricula__pb2.Matricula.SerializeToString,
        response_deserializer=matricula__pb2.Mess.FromString,
        )
    self.consultaAluno = channel.unary_unary(
        '/matricula.MatriculaService/consultaAluno',
        request_serializer=matricula__pb2.Matricula.SerializeToString,
        response_deserializer=matricula__pb2.Mess.FromString,
        )


class MatriculaServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def cadastraNota(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def atualizaNota(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def removeNota(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def consultaNota(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def consultaFalta(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def consultaAluno(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MatriculaServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'cadastraNota': grpc.unary_unary_rpc_method_handler(
          servicer.cadastraNota,
          request_deserializer=matricula__pb2.Matricula.FromString,
          response_serializer=matricula__pb2.Mess.SerializeToString,
      ),
      'atualizaNota': grpc.unary_unary_rpc_method_handler(
          servicer.atualizaNota,
          request_deserializer=matricula__pb2.Matricula.FromString,
          response_serializer=matricula__pb2.Mess.SerializeToString,
      ),
      'removeNota': grpc.unary_unary_rpc_method_handler(
          servicer.removeNota,
          request_deserializer=matricula__pb2.Matricula.FromString,
          response_serializer=matricula__pb2.Mess.SerializeToString,
      ),
      'consultaNota': grpc.unary_unary_rpc_method_handler(
          servicer.consultaNota,
          request_deserializer=matricula__pb2.Matricula.FromString,
          response_serializer=matricula__pb2.Mess.SerializeToString,
      ),
      'consultaFalta': grpc.unary_unary_rpc_method_handler(
          servicer.consultaFalta,
          request_deserializer=matricula__pb2.Matricula.FromString,
          response_serializer=matricula__pb2.Mess.SerializeToString,
      ),
      'consultaAluno': grpc.unary_unary_rpc_method_handler(
          servicer.consultaAluno,
          request_deserializer=matricula__pb2.Matricula.FromString,
          response_serializer=matricula__pb2.Mess.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'matricula.MatriculaService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
